# Generated by Django 5.2.7 on 2025-10-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
