# Generated by Django 5.2.7 on 2025-10-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprender', '0002_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
