# Generated by Django 5.2.7 on 2025-11-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprender', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
