# Generated by Django 5.2.7 on 2025-11-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprender', '0004_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
